### ISSUE TITLE
error when instaling o shared hosting, by git project import

### ISSUE THREAD

**Issue by ropad** [SiberianCMS/SiberianCMS#6]
I tried with the php file but it don't work

http://petricagroup.xyz/appmaker/installer/installation_database/check Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by SiberianCMS** [comment]
Hello @ropad this repository is now 2 years old, and we don't support it anymore.

Anyway ! If you want the latest SiberianCMS SAE, you can download the archive [here](http://www.siberiancms.com/version/siberian_sae.install.zip)

Please also check [this page](http://www.siberiancms.com/download/) about the installation & updates.

Also ! our new repository for the SAE release will be [https://github.com/Xtraball/SiberianCMS](https://github.com/Xtraball/SiberianCMS) 

Thank you !
